name: ktlint and build

on:
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    name: Check Code Quality and Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          base-url: ${{ secrets.BASE_URL }}
          post-url: ${{ secrets.POST_URL }}
          google-services-json: ${{ secrets.GOOGLE_SERVICES_JSON }}
          x-ncp-clovastudio-api-key: ${{ secrets.X_NCP_CLOVASTUDIO_API_KEY }}
          x-ncp-apigw-api-key: ${{ secrets.X_NCP_APIGW_API_KEY }}
          x-ncp-clovastudio-request-id: ${{ secrets.X_NCP_CLOVASTUDIO_REQUEST_ID }}

      - name: Ktlint Check
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          android: true
          fail_on_error: true
          level: warning

      - name: Build and run unit tests
        run: |
          ./gradlew build --daemon
          ./gradlew test

  androidTest:
    name: Run Instrumentation Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [ 26, 35 ]

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          base-url: ${{ secrets.BASE_URL }}
          post-url: ${{ secrets.POST_URL }}
          google-services-json: ${{ secrets.GOOGLE_SERVICES_JSON }}
          x-ncp-clovastudio-api-key: ${{ secrets.X_NCP_CLOVASTUDIO_API_KEY }}
          x-ncp-apigw-api-key: ${{ secrets.X_NCP_APIGW_API_KEY }}
          x-ncp-clovastudio-request-id: ${{ secrets.X_NCP_CLOVASTUDIO_REQUEST_ID }}

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          script: ./gradlew connectedDebugAndroidTest
